apiVersion: batch/v1
kind: Job
metadata:
  name: reset-argocd-admin
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: reset
        image: quay.io/argoproj/argocd:v2.9.3
        command: ["argocd-util", "admin", "password", "MyNewArgoPassword!"]
      restartPolicy: Never
  backoffLimit: 1
